let data = [
  {
    title: 'Task manager',
    image: 'img/react-task-manager-bj.jpg',
    linkDemo: 'https://evgenbabenko.github.io/react-task-manager-bj/',
    linkCode: 'https://github.com/EvgenBabenko/react-task-manager-bj',
    linkTemplate: null,
    description: 'Another one task manager',
    tags: ['React', 'Redux', 'Material UI'],
    createdAt: '2018/09'
  },
  // {
  //   title: 'Image-loader',
  //   image: null,
  //   linkDemo: null,
  //   linkCode: 'https://github.com/EvgenBabenko/image-loader',
  //   linkTemplate: null,
  //   description: 'Image loader, convert image to binary data and render with Ractive.js',
  //   tags: ['Ractive', 'Bootstrap', 'Webpack'],
  //   createdAt: '2018/09'
  // },
  {
    title: 'Stripo',
    image: 'img/react-stripo.jpg',
    linkDemo: 'https://evgenbabenko.github.io/react-stripo/',
    linkCode: 'https://github.com/EvgenBabenko/react-stripo',
    linkTemplate: null,
    description: 'Simple Stripo - editing templates',
    tags: ['React', 'Redux', 'Material UI'],
    createdAt: '2018/08'
  },
  {
    title: 'Task manager',
    image: null,
    linkDemo: null,
    linkCode: 'https://github.com/EvgenBabenko/incode-compose',
    linkTemplate: null,
    description: 'FullStack application (MERN stack)',
    tags: ['React', 'Redux', 'Material UI', 'Node', 'Express', 'MongoDB'],
    createdAt: '2018/06'
  },
  {
    title: 'Info list',
    image: 'img/react-info-list.jpg',
    linkDemo: 'https://evgenbabenko.github.io/react-info-list/',
    linkCode: 'https://github.com/EvgenBabenko/react-info-list',
    linkTemplate: null,
    description: 'Simple info list.',
    tags: ['React', 'Redux', 'Semantic UI'],
    createdAt: '2018/05'
  },
  {
    title: 'Web search',
    image: null,
    linkDemo: null,
    linkCode: 'https://github.com/EvgenBabenko/ts-web-search',
    linkTemplate: null,
    description: 'Clearly web search based on Google search',
    tags: ['TypeScript', 'Webpack'],
    createdAt: '2018/05'
  },
  {
    title: 'Nearby place',
    image: null,
    linkDemo: null,
    linkCode: 'https://github.com/EvgenBabenko/ts-nearby-place',
    linkTemplate: null,
    description: 'Get nearby places with input users lat/lng',
    tags: ['TypeScript', 'Google API', 'Webpack'],
    createdAt: '2018/05'
  },
  {
    title: 'Trello',
    image: null,
    linkDemo: null,
    linkCode: 'https://github.com/EvgenBabenko/react-trello',
    linkTemplate: null,
    description: 'Simple trello clone',
    tags: ['React', 'Bootstrap'],
    createdAt: '2018/03'
  },
  // {
  //     title: 'Tag list',
  //     image: 'img/tag-list.jpg',
  //     linkDemo: 'works/tag-list-react/index.html',
  //     linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/tag-list-react',
  //     linkTemplate: null,
  //     description: 'Several tag list could be inserted in a page. Built with React',
  //     tags: ['React', 'Bootstrap'],
  //     createdAt: 2018/02,
  // },
  {
    title: 'This Portfolio',
    image: 'img/portfolio.jpg',
    linkDemo: 'https://evgenbabenko.github.io/',
    linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io',
    linkTemplate: null,
    description: 'Allmost all DOM generated by JavaScript, used Saas preprocessor',
    tags: ['JavaScript', 'HTML/CSS', 'Sass', 'Flexbox', 'Gulp'],
    createdAt: '2017/07'
  },
  {
    title: 'Find the pair',
    image: 'img/find-the-pair.jpg',
    linkDemo: 'https://EvgenBabenko.github.io/find-the-pair/index.html',
    linkCode: 'https://github.com/EvgenBabenko/find-the-pair',
    linkTemplate: 'http://mypuzzle.org/find-the-pair',
    description: 'Game "Find a pair", no frameworks, no libraries, pure JavaScript',
    tags: ['JavaScript'],
    createdAt: '2017/12'
  },
  {
    title: 'Adverting',
    image: 'img/ad.jpg',
    linkDemo: 'https://EvgenBabenko.github.io/ad/build/index.html',
    linkCode: 'https://github.com/EvgenBabenko/ad',
    linkTemplate:
      'https://www.google.com/doubleclick/studio/externalpreview/#/bjRxbk4BTA6eGZbcSRDwEA?creativeId=41752966',
    description: 'Adverting Samsung Galaxy S7, no frameworks, no libraries, pure JavaScript',
    tags: ['JavaScript', 'Gulp'],
    createdAt: '2017/10'
  },
  {
    title: 'Tag list',
    image: 'img/tag-list.jpg',
    linkDemo: 'works/tag-list/index.html',
    linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/tag-list',
    linkTemplate: null,
    description: 'Several tag list could be inserted in a page. Built on prototypes',
    tags: ['JavaScript', 'jQuery', 'Bootstrap'],
    createdAt: '2018/02'
  },
  {
    title: 'Slider',
    image: 'img/slider.jpg',
    linkDemo: 'works/slider/index.html',
    linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/slider',
    linkTemplate: null,
    description: 'Several sliders could be inserted in a page. Built on prototypes',
    tags: ['JavaScript', 'jQuery'],
    createdAt: '2018/01'
  },
  {
    title: 'Form validation',
    image: 'img/form-validation.jpg',
    linkDemo: 'works/form-validation/index.html',
    linkCode:
      'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/form-validation',
    linkTemplate: null,
    description: 'Form validation with AJAX',
    tags: ['JavaScript', 'AJAX'],
    createdAt: '2018/01'
  },
  {
    title: 'Timer',
    image: 'img/timer.jpg',
    linkDemo: 'works/timer/index.html',
    linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/timer',
    linkTemplate: null,
    description: 'Several timers could be inserted in a page. Built on prototypes',
    tags: ['JavaScript'],
    createdAt: '2018/01'
  },
  // {
  //     title: 'JavaScript',
  //     image: 'img/java-script.jpg',
  //     linkDemo: 'works/java-script/build/index.html',
  //     linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/java-script',
  //     linkTemplate: null,
  //     description: 'JavaScript online courses, http://jscourse.com/',
  //     tags: ['JavaScript', 'jQuery', 'Gulp', 'Pug'],
  //     createdAt: '2017/10',
  // },
  {
    title: 'Modern corporate design',
    image: 'img/modern-corporate-design.jpg',
    linkDemo: 'works/modern-corporate-design/build/index.html',
    linkCode:
      'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/modern-corporate-design',
    linkTemplate: 'http://www.pcklab.com/templates/modern-corporate-design',
    description:
      'Converted PSD to HTML, responsive site (7 pages), cross-browser compatibility (modern browser, IE11)',
    tags: ['HTML/CSS', 'Flexbox', 'SCSS', 'jQuery', 'Gulp'],
    createdAt: '2017/09'
  },
  // {
  //     title: 'Responsive template',
  //     image: 'img/responsive-PSD.jpg',
  //     linkDemo: 'works/responsive-PSD-template/index.html',
  //     linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/responsive-PSD-template',
  //     linkTemplate: 'http://blazrobar.com/free-psd-website-templates/responsive-psd-template/',
  //     description: 'Converted PSD to HTML, Responsive single page',
  //     tags: ['HTML/CSS', 'Flexbox', 'Sass', 'Mobile First'],
  //     createdAt: '2017/08',
  // },
  {
    title: 'Change is Coming',
    image: 'img/change-is-coming.jpg',
    linkDemo: 'works/change-is-coming/index.html',
    linkCode:
      'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/change-is-coming',
    linkTemplate: 'http://www.pcklab.com/templates/change-coming',
    description: 'Converted PSD to HTML, responsive single page',
    tags: ['HTML/CSS', 'Flexbox', 'SCSS'],
    createdAt: '2017/06'
  },
  {
    title: 'Landing Page',
    image: 'img/landing-page.jpg',
    linkDemo: 'works/landing-page/index.html',
    linkCode:
      'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/landing-page',
    linkTemplate: 'http://www.pcklab.com/templates/landing-page',
    description: 'Converted PSD to HTML, responsive single page',
    tags: ['HTML/CSS', 'Flexbox', 'SCSS'],
    createdAt: '2017/06'
  }
  // {
  //     title: 'Clean Corporate Design',
  //     image: 'img/clean-corporate-design.jpg',
  //     linkDemo: 'works/clean-corporate-design/index.html',
  //     linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/clean-corporate-design',
  //     linkTemplate: 'http://www.pcklab.com/templates/clean-corporate-design',
  //     description: 'Converted PSD to HTML, responsive single page',
  //     tags: ['HTML/CSS', 'Flexbox'],
  //     createdAt: '2017/08',
  // },
  // {
  //     title: 'The Portfolio',
  //     image: 'img/theportfolio.jpg',
  //     linkDemo: 'works/theportfolio/index.html',
  //     linkCode: 'https://github.com/EvgenBabenko/EvgenBabenko.github.io/tree/master/works/theportfolio',
  //     linkTemplate: 'http://www.pcklab.com/templates/portfolio',
  //     description: 'Converted PSD to HTML, single page',
  //     tags: ['HTML/CSS'],
  //     createdAt: '2017/06',
  // }
];
